controllers:
    resource: ../src/Controller/
    type: attribute

listerInstrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument

InstrumentConsulter:
        path: /instrument/consulter/{id}
        controller: App\Controller\InstrumentController::consulterInstrument

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouterCours

coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours

coursSupprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCours